zabbix-ext-all-templates:
  image: monitoringartist/zabbix-ext-all-templates:latest
zabbix-db-storage:
  restart: always
  image: busybox:latest
  volumes:
    - /var/lib/mysql
zabbix-db:
  image: monitoringartist/zabbix-db-mariadb
  restart: always
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /reworks/zabbix/backups:/backups
  volumes_from:
    - zabbix-db-storage
  env_file:
    - ./config/db/env
zabbix:
  image: monitoringartist/zabbix-3.0-xxl:3.0.4
  restart: always
  ports:
    - 8080:80
    - 10051:10051
  volumes:
    - /etc/localtime:/etc/localtime:ro
  volumes_from:
    - zabbix-ext-all-templates
  links:
    - zabbix-db
  env_file:
    - ./config/zabbix/env
 
